language: python
# cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
# command to install dependencies
install: make install
# command to run tests
script: make test
# send coverage report
after_success: bash <(curl -s https://codecov.io/bash)
